# .github/workflows/_dbx-deploy.yml
name: Reusable - Databricks Deploy (PAT)

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      working_directory:
        default: "Azure/Databricks"
        type: string
      run_job_name:
        required: false
        type: string
    secrets:
      DATABRICKS_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    env:
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_BUNDLE_ENV: ${{ inputs.environment_name }}

    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Show CLI version
        run: databricks -v
      - name: Validate bundle
        working-directory: ${{ inputs.working_directory }}
        run: databricks bundle validate
      - name: Deploy bundle
        working-directory: ${{ inputs.working_directory }}
        run: databricks bundle deploy --auto-approve
      - name: Run job (optional)
        if: ${{ inputs.run_job_name }}
        working-directory: ${{ inputs.working_directory }}
        run: databricks bundle run "${{ inputs.run_job_name }}" --refresh-all
