# .github/workflows/cicd.yml
name: Databricks CI/CD (PAT)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment_name:
        description: "dev | test | prod"
        required: true
        default: "test"
        type: choice
        options: [ "dev", "test", "prod" ]
      run_job_name:
        description: "Optional bundle job to run after deploy"
        required: false

jobs:
  dev-on-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_dbx-deploy.yml
    with:
      environment_name: dev
      working_directory: Azure/Databricks
      run_job_name: notebooks_job           # <- change to your job name or remove
    secrets: inherit

  manual-promote:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/_dbx-deploy.yml
    with:
      environment_name: ${{ inputs.environment_name }}
      working_directory: Azure/Databricks
      run_job_name: ${{ inputs.run_job_name }}
    secrets: inherit
